### ISSUE TITLE
Error when overriding createUser

### ISSUE THREAD

**Issue by lauyilouis** [cult-of-coders/meteor-apollo-accounts#4]
My code:
```
overrideCreateUser: (createUser, _, args, context) => {
    // Optionally override createUser if you need custom logic
    // Or simply restrict him from authenticating
    return createUser.call(null, ...args);
},
```

The error:
```
W20181002-02:38:12.299(8)? (STDERR) TypeError: undefined is not a function
W20181002-02:38:12.299(8)? (STDERR)     at Object.overrideCreateUser (imports/graphql/account/index.js:19:23)
W20181002-02:38:12.299(8)? (STDERR)     at Promise.asyncApply (packages/cultofcoders:apollo-accounts/src/Mutation/index.js:28:24)
```

**Comment by lauyilouis** [comment]
changed
```
return createUser.call(null, ...args);
```
to
```
const { username, password } = args;
return createUser(null, { username, password });
```
made it works
